### ISSUE TITLE
[Technical Initiative Funding Request]: Test

### ISSUE THREAD

**Issue by riaankleinhans** [riaankleinhans/tac-gitvote-test#2]
### Technical Initiative

Test

### Lifecycle Phase

Sanbox

### Funding amount

$1000

### Problem Statement

Test

### Who does this affect?

Test

### Have there been previous attempts to resolve the problem?

Test

### Why should it be tackled now and by this TI?

Test

### Give an idea of what is required to make the funding initiative happen

Test

### What is going to be needed to deliver this funding initiative?

Test

### Give a summary of the requirements that contextualize the costs of the funding initiative

Test

### Who is responsible for doing the work of this funding initiative?

Test

### Who is accountable for doing the work of this funding initiative?

Test

### If the responsible or accountable parties are no longer available, what is the backup contact or plan?

Test

### What license is this funding initiative being used under?

Test

### Code of Conduct

- [X] I agree to follow the OpenSSF's Code of Conduct

### List the major milestones by date and identify the overall timeline within which the technical initiative plans to accomplish their goals. Any payments for services, sponsorships, etc., will require LF Legal and Financial review.

Test

**Comment by SecurityCRob** [comment]
👍

**Comment by riaankleinhans** [comment]
:+1:

**Comment by SecurityCRob** [comment]
> ## Vote created
> 
> **@riaankleinhans** has called for a vote on `[Technical Initiative Funding Request]: Test` (#2).
> 
> The following users have binding votes:
> User
> @riaankleinhans
> @crob
> 
> Non-binding votes are also appreciated as a sign of support!
> ## How to vote
> 
> You can cast your vote by reacting to `this` comment. The following reactions are supported:
> In favor 	Against 	Abstain
> 👍 	👎 	👀
> 
> _Please note that voting for multiple options is not allowed and those votes won't be counted._
> 
> The vote will be open for `5days`. It will pass if at least `50%` of the users with binding votes vote `In favor 👍`. Once it's closed, results will be published here as a new comment.

👍
